[build]
  publish = "/"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/index_en.html"
  to = "/index_en/"
  status = 301

[[redirects]]
  from = "/resume_en.html"
  to = "/resume_en/"
  status = 301

[[redirects]]
  from = "/index_fr.html"
  to = "/index_fr/"
  status = 301

[[redirects]]
  from = "/resume_fr.html"
  to = "/resume_fr/"
  status = 301

[[redirects]]
  from = "/en"
  to = "/index.html"
  status = 302

[[redirects]]
  from = "/fr"
  to = "/index.html"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200